# configuration for https://github.com/caksoylar/keymap-drawer
parse_config:
  raw_binding_map:
    '&sys_reset': Reset
    '&bootloader': Boot
    '&swapper': Win Next
    '&caps_word': Caps Word
    '&inv_qm': ¿

    '&kp LC(LG(LEFT))': Desk Left
    '&kp LC(LG(RIGHT))': Desk Right
    '&kp LC(TAB)': Tab Right
    '&kp LC(LS(TAB))': Tab Left
    '&kp LA(F4)': Win Close
    '&kp LC(F4)': Tab Close
    '&kp LS(TAB)': Win Prev
    '&kp LS(INS)': Paste
    '&kp LG(L)': Lock

    '&to 4': Game
    '&to 0': Default

    '&out OUT_USB': Out USB
    '&out OUT_BLE': Out BLE

    '&bt BT_SEL 0': BT 1
    '&bt BT_SEL 1': BT 2
    '&bt BT_SEL 2': BT 3
    '&bt BT_SEL 3': BT 4
    '&bt BT_SEL 4': BT 5

    '&mmv MOVE_UP': Mouse ↑
    '&mmv MOVE_DOWN': Mouse ↓
    '&mmv MOVE_LEFT': Mouse ←
    '&mmv MOVE_RIGHT': Mouse →

    '&msc SCRL_UP': Scroll ↑
    '&msc SCRL_DOWN': Scroll ↓
    '&msc SCRL_LEFT': Scroll ←
    '&msc SCRL_RIGHT': Scroll →

    '&mkp LCLK': Left Click
    '&mkp RCLK': Right Click
    '&mkp MCLK': Middle Click
    '&mkp MB4': Back Click
    '&mkp MB5': Forward Click

  sticky_label: $$mdi:gesture-tap-hold$$
  trans_legend:
    tap: $$mdi:transfer$$
    type: trans

  mark_alternate_layer_activators: true


  zmk_combos:
    combo_tab:    {align: top, o: 0.15}
    combo_del:    {align: top, o: 0.15}
    combo_f12:    {align: bottom}
    combo_btclr:  {align: bottom}
    combo_play:   {align: right}
    combo_capswd: {draw_separate: true}
    combo_semi:   {draw_separate: true}
    combo_grave:  {draw_separate: true}
    combo_lpar:   {draw_separate: true}
    combo_rpar:   {draw_separate: true}
    combo_lbkt:   {draw_separate: true}
    combo_rbkt:   {draw_separate: true}
    combo_tab:    {draw_separate: true}
    combo_del:    {draw_separate: true}
    combo_esc:    {draw_separate: true}
    combo_ret:    {draw_separate: true}
    combo_lock:   {draw_separate: true}
    combo_bslh:   {draw_separate: true}
    combo_slsh:   {draw_separate: true}

  #  zmk_keycode_map:
  #   # Symbols
  #   EXCLAMATION: "!"
  #   EXCL: "!"
  #   AT_SIGN: "@"
  #   AT: "@"
  #   HASH: "#"
  #   POUND: "#"
  #   DOLLAR: $
  #   DLLR: $
  #   PERCENT: "%"
  #   PRCNT: "%"
  #   CARET: ^
  #   AMPERSAND: "&"
  #   AMPS: "&"
  #   ASTERISK: "*"
  #   ASTRK: "*"
  #   STAR: "*"
  #   LEFT_PARENTHESIS: (
  #   LPAR: (
  #   RIGHT_PARENTHESIS: )
  #   RPAR: )
  #   EQUAL:
  #     tap: "="
  #     shifted: "+"
  #   PLUS: +
  #   MINUS:
  #     tap: "-"
  #     shifted: "_"
  #   UNDERSCORE: _
  #   UNDER: _
  #   SLASH:
  #     tap: "/"
  #     shifted: "?"
  #   FSLH:
  #     tap: "/"
  #     shifted: "?"
  #   QUESTION: "?"
  #   QMARK: "?"
  #   BACKSLASH:
  #     tap: '\'
  #     shifted: "|"
  #   BSLH:
  #     tap: '\'
  #     shifted: "|"
  #   PIPE: "|"
  #   NON_US_BACKSLASH: \
  #   PIPE2: "|"
  #   NON_US_BSLH: "|"
  #   SEMICOLON:
  #     tap: ";"
  #     shifted: ":"
  #   SEMI:
  #     tap: ";"
  #     shifted: ":"
  #   COLON: ":"
  #   SINGLE_QUOTE:
  #     tap: "'"
  #     shifted: '"'
  #   SQT:
  #     tap: "'"
  #     shifted: '"'
  #   APOSTROPHE: <
  #   APOS: .
  #   DOUBLE_QUOTES: '"'
  #   DQT: '"'

  #   LESS_THAN: <
  #   LT: <
  #   DOT:
  #     tap: "."
  #     shifted: ">"
  #   COMMA:
  #     tap: ","
  #     shifted: "<"
  #   GREATER_THAN: ">"
  #   GT: ">"
  #   LEFT_BRACKET:
  #     tap: "["
  #     shifted: "{"
  #   LBKT:
  #     tap: "["
  #     shifted: "{"
  #   LEFT_BRACE: "{"
  #   LBRC: "{"
  #   RIGHT_BRACKET:
  #     tap: "]"
  #     shifted: "}"
  #   RBKT:
  #     tap: "]"
  #     shifted: "}"
  #   RIGHT_BRACE: "}"
  #   RBRC: "}"
  #   GRAVE:
  #     tap: "`"
  #     shifted: "~"
  #   TILDE: "~"
  #   NON_US_HASH: "#"
  #   NUHS: "#"
  #   TILDE2: "~"

  #   # Numbers
  #   N1:
  #     tap: 1
  #     shifted: "!"
  #   N2:
  #     tap: 2
  #     shifted: "@"
  #   N3:
  #     tap: 3
  #     shifted: "#"
  #   N4:
  #     tap: 4
  #     shifted: "$"
  #   N5:
  #     tap: 5
  #     shifted: "%"
  #   N6:
  #     tap: 6
  #     shifted: "^"
  #   N7:
  #     tap: 7
  #     shifted: "&"
  #   N8:
  #     tap: 8
  #     shifted: "*"
  #   N9:
  #     tap: 9
  #     shifted: "("
  #   N0:
  #     tap: 0
  #     shifted: ")"

  #   # Modifiers
  #   LCTRL: $$mdi:apple-keyboard-control$$
  #   LALT: $$mdi:apple-keyboard-option$$
  #   LSHIFT: $$mdi:apple-keyboard-shift$$
  #   LSHFT: $$mdi:apple-keyboard-shift$$
  #   LCMD: $$mdi:apple-keyboard-command$$
  #   RCTRL: $$mdi:apple-keyboard-control$$
  #   RALT: $$mdi:apple-keyboard-option$$
  #   RSHIFT: $$mdi:apple-keyboard-shift$$
  #   RSHFT: $$mdi:apple-keyboard-shift$$
  #   RCMD: $$mdi:apple-keyboard-command$$
  #   # "Meh" key
  #   LS(LC(LALT)): $$mdi:star-three-points$$

  #   # Arrows
  #   UP: $$mdi:arrow-up-bold$$
  #   DOWN: $$mdi:arrow-down-bold$$
  #   LEFT: $$mdi:arrow-left-bold$$
  #   RIGHT: $$mdi:arrow-right-bold$$

  #   # Whitespace
  #   ENTER:
  #     type: enter
  #     tap: $$mdi:keyboard-return$$
  #   ESC: $$mdi:keyboard-esc$$
  #   TAB: $$mdi:keyboard-tab$$
  #   LS(TAB): $$mdi:keyboard-tab-reverse$$
  #   SPACE: $$mdi:keyboard-space$$
  #   BACKSPACE:
  #     type: backspace
  #     tap: $$mdi:backspace$$
  #   BSPC:
  #     type: backspace
  #     tap: $$mdi:backspace$$
  #   DELETE: $$mdi:backspace-reverse-outline$$
  #   DEL: $$mdi:backspace-reverse-outline$$

  #   # Locks
  #   CAPSLOCK: $$mdi:apple-keyboard-caps$$
  #   CAPS: $$mdi:apple-keyboard-caps$$

  #   # Sound
  #   C_MUTE: $$mdi:volume-off$$
  #   C_VOL_UP: $$mdi:volume-high$$
  #   C_VOL_DN: $$mdi:volume-low$$

  #   # Media
  #   C_NEXT: $$mdi:skip-next$$
  #   C_PREV: $$mdi:skip-previous$$
  #   C_PP: $$mdi:play-pause$$

  #   # Bluetooth
  #   BT_CLR: $$mdi:bluetooth-off$$
  #   BT_SEL: $$mdi:bluetooth-connect$$

  #   # Settings
  #   C_BRI_UP: $$mdi:brightness-5$$
  #   C_BRI_DN: $$mdi:brightness-7$$

  #   # System
  #   C_POWER: $$mdi:power-standby$$
  #   C_AL_LOCK: $$mdi:lock$$
  #   K_CANCEL: $$mdi:close-box$$

  #   # Zoom
  #   RG(RS(A)):
  #     tap: $$mdi:microphone$$
  #     hold: zoom
  #   RG(RS(V)):
  #     tap: $$mdi:video$$
  #     hold: zoom

 zmk_keycode_map:
    # custom mappings
    C_VOL_UP: Vol Up
    C_VOL_DN: Vol Down
    C_AL_CALC: Calc
    C_PP: Play Pause

    LCTRL: Ctrl
    RCTRL: Ctrl
    LALT: Alt
    RALT: Alt
    LGUI: Gui
    RGUI: Gui
    LSHFT: Shift
    RSHFT: Shift
    ESC: Esc
    SPACE: ␣
    BSPC: ⌫
    RET: ⏎
    TAB: ↹
    DEL: ⌦

    PG_UP: Page Up
    PG_DN: Page Down
    INS: Insert
    HOME: Home
    END: End
    CAPS: Caps Lock
    PSCRN: Print Scrn
    PAUSE_BREAK: Pause Break

    UP: ↑
    DOWN: ↓
    LEFT: ←
    RIGHT: →

    C_PP: ⏯
    C_NEXT: ⏭️
    C_PREV: ⏮️

    # defaults
    AMPERSAND: '&'
    AMPS: '&'
    APOS: "'"
    APOSTROPHE: "'"
    ASTERISK: '*'
    ASTRK: '*'
    AT: '@'
    AT_SIGN: '@'
    BACKSLASH: \
    BSLH: \
    CARET: ^
    COLON: ':'
    COMMA: ','
    DLLR: $
    DOLLAR: $
    DOT: .
    DOUBLE_QUOTES: '"'
    DQT: '"'
    EQUAL: '='
    EXCL: '!'
    EXCLAMATION: '!'
    FSLH: /
    GRAVE: '`'
    GREATER_THAN: '>'
    GT: '>'
    HASH: '#'
    LBKT: '['
    LBRC: '{'
    LEFT_BRACE: '{'
    LEFT_BRACKET: '['
    LEFT_PARENTHESIS: (
    LESS_THAN: <
    LPAR: (
    LT: <
    MINUS: '-'
    NON_US_BACKSLASH: \
    NON_US_BSLH: '|'
    NON_US_HASH: '#'
    NUHS: '#'
    PERCENT: '%'
    PERIOD: .
    PIPE: '|'
    PIPE2: '|'
    PLUS: +
    POUND: '#'
    PRCNT: '%'
    QMARK: '?'
    QUESTION: '?'
    RBKT: ']'
    RBRC: '}'
    RIGHT_BRACE: '}'
    RIGHT_BRACKET: ']'
    RIGHT_PARENTHESIS: )
    RPAR: )
    SEMI: ;
    SEMICOLON: ;
    SINGLE_QUOTE: ''''
    SLASH: /
    SQT: ''''
    STAR: '*'
    TILDE: '~'
    TILDE2: '~'
    UNDER: _
    UNDERSCORE: _


draw_config:
  # combo box dimensions
  combo_w: 36
  combo_h: 36
  
  footer_text: 'Created with <a href="https://github.com/caksoylar/keymap-drawer">keymap-drawer</a>'
  dark_mode: auto